name: renovate

on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '36 5 * * 1'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: Djiit/action-renovate@master
        with:
          args: >
            ${{ github.repository }}
          # --more-args
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
